### ISSUE TITLE
Homepage - Content(Latest News Section): "2016" should be "2013" as per existing site or not?

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Automatic-Transmissions-R-Us#1]
![image](https://cloud.githubusercontent.com/assets/18587097/16641660/0ee07da8-442d-11e6-8229-f17f9ea2a5a9.png)

**Comment by ralphtitan** [comment]
Since the old site used custom post type for the 'Latest News', and this rebuilt site now uses default wordpress posts for the 'Latest News', the content had to be populated manually for this, hence showing this year's date. But anyway it's now fixed. Thanks
